# Generated by Django 3.2.7 on 2021-12-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='profile',
        ),
    ]
